project:
  type: website
  resources:
    - objects.txt

metadata-files:
  - _sidebar.yml

filters:
  - interlinks

lightbox: auto

website:
  title: "chatlas"
  # bread-crumbs: true
  repo-url: https://github.com/cpsievert/chatlas
  repo-actions: [issue, source]

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: Reference
        href: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/cpsievert/chatlas
        aria-label: GitHub repository


quartodoc:
  package: chatlas
  render_interlinks: true
  sidebar: _sidebar.yml
  sections:
    - title: Chat model providers
      desc: Start a chat with a particular large language model (llm) provider.
      contents:
        - ChatAnthropic
        - ChatAzureOpenAI
        - ChatBedrockAnthropic
        - ChatGithub
        - ChatGoogle
        - ChatGroq
        - ChatOllama
        - ChatOpenAI
        - ChatPerplexity
    - title: The chat object
      desc: Methods and attributes available on a chat instance
      contents:
        - Chat
    - title: Image input
      desc: Submit image input to the chat
      contents:
        - image_file
        - image_plot
        - image_url
    - title: Tool calling
      desc: Add context to python function before registering it as a tool.
      contents:
        - Tool
    - title: Turns
      desc: A provider-agnostic representation of content generated during an assistant/user turn.
      contents:
        - Turn
    - title: Query token usage
      contents:
        - token_usage
    - title: Implement a model provider
      contents:
        - Provider
    - title: User-facing types
      contents:
        - types.Content
        - types.ContentImage
        - types.ContentImageInline
        - types.ContentImageRemote
        - types.ContentJson
        - types.ContentText
        - types.ContentToolRequest
        - types.ContentToolResult
        - types.ImageContentTypes
        - types.MISSING_TYPE
        - types.MISSING
        - types.SubmitInputArgsT
        - types.TokenUsage


interlinks:
  fast: true
  sources:
    python:
      url: https://docs.python.org/3/
    pydantic:
      url: https://docs.pydantic.dev/latest/

editor:
  render-on-save: true
  markdown:
    canonical: true
    wrap: sentence
